### ISSUE TITLE
Exporting currently playing title

### ISSUE THREAD

**Issue by Juke1999** [Xerus2000/monsterutilities#101]
Hey there!
Automatically exporting the currently playing title as a .txt file would be a helpful feature for livestreamers and other broadcasters.

Cheers
Justin

**Comment by Xerus2000** [comment]
See https://github.com/Xerus2000/monsterutilities/pull/73

**Comment by Juke1999** [comment]
Oops, missed that. Sorry!

**Comment by defvs** [comment]
Soon will be added to main branch :)
