### ISSUE TITLE
404 Site not found

### ISSUE THREAD

**Issue by Muffl0n-DE** [Xerus2000/monsterutilities#105]
The site (http://monsterutilities.bplaced.net/) is no longer available

**Comment by defvs** [comment]
We are slowly transitioning to Github Releases. Please use https://github.com/Xerus2000/monsterutilities/releases for latest releases.
@Xerus2000 can you remove the old website from the header ?

**Comment by Xerus2000** [comment]
Yes that's right - I've removed it :)
