### ISSUE TITLE
Gold subscription not acknowledged

### ISSUE THREAD

**Issue by Swiftb0y** [xerus2000/monsterutilities#108]
I have a valid account with an active gold subscription, but the monsterutilities doesn't acknowledge that. This obviously breaks the downloading functionality completely, since instead of starting the download, the Button keeps saying "No Gold subscription" and keeps trying to verify the account.

**Comment by defvs** [comment]
Yup, seems like a bug to me, the API endpoint has changed apparently ?

**Comment by defvs** [comment]
Okay, the API definitely changed. ``goldService`` is now named ``hasGold``, easy fix.
