### ISSUE TITLE
No licensable tracks?

### ISSUE THREAD

**Issue by haxer103** [xerus2000/monsterutilities#113]
Hi!

First of all my intention was to dowanload all licensable tracks.
Logged in and clicked the "Enabled Streamer Mode" setting, and then I wasn't able to play or download any song.
Opened the releases.json from the cache and all songs are set to '"licensable" : false,' any idea why or maybe its a bug?
Tried restarting and clearing the cache.

Thx for any help :)

**Comment by defvs** [comment]
Any chance you not logged in as gold ? all tracks show up as not licensable. Please try to input your connect.sid or use the login button and report back.

**Comment by haxer103** [comment]
I would say it looks like I am signed in. ID is Filled and I only have the downlod button, where the Login button was. Also downloads work when streamer mode is disabled.

**Comment by defvs** [comment]
I will investigate this then, might be an issue with the new API
