### ISSUE TITLE
Error downloading most WAV files

### ISSUE THREAD

**Issue by 62274677** [xerus2000/monsterutilities#119]
When downloading tracks in .wav there is an error:

> 22:05:18 Error downloading Bensley - All Night: WrongResponseTypeException: Error downloading https://connect.monstercat.com/v2/release/4e3610b1-59d4-498b-be3c-1c7d36abdca9/track-download/4815dffc-60e8-450d-986a-d10fd618b994?format=wav: file type binary/octet-stream unexpected!

This does not happen to all files, but does happen to most.
![image](https://user-images.githubusercontent.com/36176438/84325886-a730e200-ab30-11ea-86bf-6862d1e5ac2e.png)

**Comment by danomate** [comment]
Just experienced this error on 64-bit windows version. dev 213
![image](https://user-images.githubusercontent.com/21294990/85636282-360c3580-b6bf-11ea-9bcf-d4aa61973b28.png)

**Comment by defvs** [comment]
Issue already been fixed but not yet released. Please be patient until we compile a new release.
