### ISSUE TITLE
Replace XerusLogger with slf4j

### ISSUE THREAD

**Issue by Xerus2000** [Xerus2000/monsterutilities#14]
My custom-built logger is simply not fit for this project anymore, it is only a perk intended for small projects to avoid Sysout. Thus slf4j should be used, together with KotlinLogging and bound to a binding.

This also makes us independent of [this incredibly annoying Intellij IDEA bug](https://youtrack.jetbrains.com/issue/KT-21863)

**Comment by fwcd** [comment]
@Xerus2000 What might be possible, is to create a global 'logger' object that uses Kotlin's delegation mechanism to call XerusLogger instead of a typealias. But in the long run, it might indeed be better to switch to slf4j.
