### ISSUE TITLE
Add automated tests

### ISSUE THREAD

**Issue by Xerus2000** [Xerus2000/monsterutilities#16]
To avoid accidentally breaking stuff, there should be automatic tests. Help is appreciated since I have no experience in this subject yet.

**Comment by fwcd** [comment]
@Xerus2000 Unit testing is actually not that hard, since it is baked right into Gradle. You begin with a folder structure like this:

```
src
├───main
│   └───kotlin
└───test
    └───kotlin
```

Then you simply add test classes to src/test/kotlin. Test classes use the testing framework JUnit, which essentially provides you with a bunch of methods to check whether certain conditions are true (so called 'assertions'). JUnit needs to be added as a 'testCompile' or 'testImplementation' dependency in your buildfile. A basic test class could look something like this:

```kotlin
import org.junit.Assert.assertTrue

class ArithmeticTest {
    @Test fun additionTest() {
        assertTrue((2 + 2) == 4)
    }
}
```

To run all of your tests, simply run `gradle test` or use `gradle build`, in which case all tests will be automatically executed after your build.

**Comment by fwcd** [comment]
@Xerus2000 An advantage of using Gradle wrappers (or Jitpack) would be that it would be trivial to setup CI badges like this:

![Build: Passing](https://raw.githubusercontent.com/dwyl/repo-badges/master/highresPNGs/build-passing.png)

CI ("continuous integration") is basically a server on the web that automatically runs all your automated tests every time you push some code to the repo. This badge (which you can paste into your README) will automatically show if your tests do not pass, so you do not have to waste your time running all tests on your local machine regularly. You can get a free CI server at https://travis-ci.org for example (my [KotlinLanguageServer project](http://github.com/fwcd/KotlinLanguageServer) uses this and it works great). GitHub will even show you on every pull request if your tests pass there:

![capture](https://user-images.githubusercontent.com/30873659/41497823-c65853a2-715d-11e8-966e-dccd1e95e304.JPG)

**Comment by Xerus2000** [comment]
Yep, I was aware of the CI part and where to put tests. 
The issue is rather how to test the GUI using something like JUnit, and actually adding useful tests.

**Comment by fwcd** [comment]
@Xerus2000 What might be possible is to use a library like [TestFX](https://github.com/TestFX/TestFX), which adds GUI-related testing functionality on top of JUnit. For example, one could automatically click a button and assert that something happens:

```kotlin
import org.testfx.framework.junit5.ApplicationTest

@ExtendWith(ApplicationExtension.class)
class ClickableButtonTest {
    @Start fun onStart(stage: Stage) {
        val button = Button("click me!")
        button.setOnAction { button.setText("clicked!") }
        stage.setScene(Scene(StackPane(button), 100, 100))
        stage.show()
    }

    @Test fun shouldContainButton() {
        verifyThat(".button", hasText("click me!"))
    }

    @Test fun shouldClickOnButton(robot: FxRobot) {
        robot.clickOn(".button")
        verifyThat(".button", hasText("clicked!"))
    }
}
```

**Comment by fwcd** [comment]
Once I get around and find some time to do so, I could create a set of tests in a PR.

**Comment by defvs** [comment]
That would be awesome as it seems neither of us knows how to setup the CI

**Comment by fwcd** [comment]
Moved the CI request to a separate issue: #23

**Comment by Xerus2000** [comment]
First test has been created with deefc50
Further ones are obviously appreciated, but the foundation is now laid, so I'll close this.
