### ISSUE TITLE
Create GitHub releases and adjust the auto-updater

### ISSUE THREAD

**Issue by Xerus2000** [Xerus2000/monsterutilities#17]
GitHub releases are probably the way to go for the future, but they should still work properly with the auto-updater. 
Furthermore, they should be fit into the gradle "release" task to automatically publish a release using the GitHub Releases API.

**Comment by fwcd** [comment]
@Xerus2000 This would integrate nicely with #23 (which could automatically deploy to the releases every time you push)

**Comment by Xerus2000** [comment]
I can already publish releases on the github-releases branch. Now the application needs to be patched so it fetches updates from the GitHub Releases.

**Comment by Xerus2000** [comment]
[ ] Do Github releases via Travis CI
[ ] Patch the Auto-updater to download new releases from Github

**Comment by Xerus2000** [comment]
Continued in #53
