### ISSUE TITLE
Songs newer than "Hush - Watervaal" cannot be played in the Player

### ISSUE THREAD

**Issue by defvs** [Xerus2000/monsterutilities#20]

**Comment by Xerus2000** [comment]
I am investigating and have already contacted Vindexus. He said that the MP3s in the blobs now contain less headers, apparently GStreamer thus fails to recognise the file.

**Comment by Xerus2000** [comment]
The issue is resolved by updating to JDK 10. I'll elaborate on this in #22

**Comment by defvs** [comment]
Fixed even on Java 8 ?

**Comment by Xerus2000** [comment]
Oh really, looks like it. Maybe they fixed their files when they had their internal move ^^
