### ISSUE TITLE
Update to JDK 10

### ISSUE THREAD

**Issue by Xerus2000** [Xerus2000/monsterutilities#22]
Updating to JDK 10 would resolve #20, but also bring a few challenges due to encapsulation and API changes.
Nevertheless, this could also be a chance to make the application self-contained because since Java 9 modularization is supported and encouraged. Thus the application would not require a JRE installed anymore.

**Comment by defvs** [comment]
The self containement is an awesome feature. Could you give me a bit of an understanding about why JDK 10 ? Is it related to the music player plugin ?

**Comment by Xerus2000** [comment]
Because Java 9 reached end-of-life and Java 11 is unreleased.
Apparently there is a [bug in Java 8 & 9](https://bugs.openjdk.java.net/browse/JDK-8181922) that was [fixed in Java 10](http://hg.openjdk.java.net/openjfx/10-dev/rt/rev/5531fbd393a6) but not backported. I don't know whether this affects Windows. 
Maybe it's also related to a newer GStreamer version, which is used internally by MediaPlayer.

**Comment by defvs** [comment]
Can't you just fork the fix from java 10 to your util project and use the class ?

**Comment by Xerus2000** [comment]
Unfortunately it's not that easy. There's a lot of other stuff involved in building JDK classes. Also, I think the songs work fine again. There's only few songs that can't be played.
Self-containment us the real goal here. Without self-containment it's annoying to depend on Java 10, nobody has it installed.
