### ISSUE TITLE
Compiling without gradle wrapper

### ISSUE THREAD

**Issue by Swiftb0y** [Xerus2000/monsterutilities#39]
You (accidentally?) removed the gradle wrapper bash script in your [latest commit](https://github.com/Xerus2000/monsterutilities/commit/c5718d7e76a4732b7124ede378e6e8b2f8a00125). Is this intentional and if so, how would you recommend to build the project without it?

**Comment by Xerus2000** [comment]
oh, that was entirely accidental

**Comment by Swiftb0y** [comment]
Ok, good to know. Could you please quickly push a fix?
