### ISSUE TITLE
Most of the catalog isn't showing up in the selection box

### ISSUE THREAD

**Issue by ReHWolution** [Xerus2000/monsterutilities#42]
As the title says, it seems like there's an issue with the catalog. It's missing a lot of songs, basically prior to 2019. Did Monstercat change something on their side?

**Comment by Xerus2000** [comment]
It is fetched directly from https://docs.google.com/spreadsheets/d/116LycNEkWChmHmDK2HM2WV85fO3p3YTYDATpAthL8_g, Monstercat has no part in this. 

For me it displays everything completely fine.

**Comment by ReHWolution** [comment]
I was talking about the Download tab. I only get Uncaged vol. 6, and the only 4 last months of songs, no matter what I put in the date field. I tried "After" 2012 january, before 2019 april, nothing works. I only see a small part of the entire library...

**Comment by Xerus2000** [comment]
Ah I see. Yes, seems to be a change in the Monstercat API. I will investigate soon.

**Comment by ReHWolution** [comment]
thanks!

**Comment by smicbee** [comment]
are there already news on this issue?

**Comment by Xerus2000** [comment]
Unfortunately this will require a bit of rethinking and I am currently working on other projects. So, sadly no, but I will definitely make time for it at some point.

**Comment by eratosthene** [comment]
It looks like there's some sort of paging in play now. If you look at the json returned by /catalog/release, the following fields show up:
`  "skip": 0,
  "total": 1469,
  "limit": 50`
So there's probably some way to page through the results.

**Comment by Xerus2000** [comment]
Yep, I have worked with that before in another query, but I have to add some logic to automatically make the necessary number of requests instead of just one as it is now.

**Comment by Xerus2000** [comment]
Fixed in 17a6ad2c702d19b2d46e614d8c303c824b416a6c
