### ISSUE TITLE
Add shuffle and replay icons

### ISSUE THREAD

**Issue by defvs** [Xerus2000/monsterutilities#5]
To make a proper player with playlist support, we need to get access to common player options like shuffle and replay

So, we will need Shuffle On/Off and Replay On/Off icons. 
Shuffle off could be two parallel arrows, while on would be the standard 🔀
For replay off, it could either be an arrow going into a wall, or simply an arrow. Replay on would of course be the arrow going back at its start

**Comment by Xerus2000** [comment]
wow everyone here focusing on the Player. I didn't think it would be, like, the biggest attraction on it ^^
I already thought of that too, but the fitting icons are required (its a custom design)

**Comment by defvs** [comment]
We still need this ASAP for Playlist. We can still use placeholders for now

**Comment by defvs** [comment]
Moving this discution to util : We merged the placeholders. Could use some custom icons though.
