### ISSUE TITLE
Connection resets bork the downloader

### ISSUE THREAD

**Issue by C0rn3j** [Xerus2000/monsterutilities#54]
`01:29:03 Error downloading Matroda - Shut It Down: SocketException: Connection reset`

Looks like the downloader doesn't retry on connection reset and will error out and enter a state where the estimated time and finish state is off.

![image](https://user-images.githubusercontent.com/1641362/59962616-2d9b8080-94e8-11e9-911a-6f9311be2146.png)

EDIT: Actually counter seems to bork even when download finishes normally

![image](https://user-images.githubusercontent.com/1641362/59962645-a13d8d80-94e8-11e9-8af8-ccfbcbfc53cb.png)

**Comment by Xerus2000** [comment]
Yeah, Connection resets are annoying. I should have fixed the counter in the latest commit though, so this confuses me a bit?

**Comment by C0rn3j** [comment]
Seems 100% reproducible so far. I just select these 3 songs and download them in FLAC.
Nothing interesting in the log however.
```
18:54:22 [JavaFX Application Thread] INFO   x.m.downloader.TabDownloader   Starting Downloader for 3 Releases with 3 Tracks
18:54:22 [mu-worker-14             ] DEBUG  x.m.downloader.Download        Downloading Project 46 & Gemellini - Deadline to /mnt/3tbRED2/MonsterTest
18:54:22 [mu-worker-28             ] DEBUG  x.m.downloader.Download        Downloading Project 46 - Reasons to /mnt/3tbRED2/MonsterTest
18:54:22 [mu-worker-29             ] DEBUG  x.m.downloader.Download        Downloading Matroda - Shut It Down to /mnt/3tbRED2/MonsterTest
```

**Comment by Xerus2000** [comment]
Hmm weird, I get no errors at all. Might it be related to your internet?

**Comment by C0rn3j** [comment]
There was no errors downloading these 3 songs, just the broken countdown.

I only got one error related to the conn reset and I think that was an actual network error, I'd just expect the client to perhaps retry a few times with a notice before ultimately failing with an error.

**Comment by Xerus2000** [comment]
oh yes, I made a dumb mistake with the counter ^^
