### ISSUE TITLE
Player sometimes mismatch songs with same name

### ISSUE THREAD

**Issue by defvs** [Xerus2000/monsterutilities#6]
E.g. : Edge of the World. Whichever you choose, you get to Razihel's.

Suggested fix : Make artist matching work, as it doesn't right now. (Player.kt, Line 195)

**Comment by Xerus2000** [comment]
oh it does? I've always wondered whether it works for every song, good hint :)

**Comment by Xerus2000** [comment]
Solved since 855e7c4
