### ISSUE TITLE
Tracks' releases are wrongly prioritized

### ISSUE THREAD

**Issue by defvs** [xerus2000/monsterutilities#60]
APIUtils.find prioritizes Best Of apparently. This causes for example coverart for Tracks to be thoses of the Best of instead of single/album/mcollection. There should be an option for which Release.Type to prioritize.

**Comment by defvs** [comment]
defvs/monsterutilities#2

**Comment by defvs** [comment]
defvs#2 has been merged into #55 
So this will be fixed with #55

**Comment by Xerus2000** [comment]
You have to add that info to the first comment of the PR for GitHub to recognise it ;)

**Comment by defvs** [comment]
Fixed with #55
