### ISSUE TITLE
APIUtils track finding is not accurate

### ISSUE THREAD

**Issue by defvs** [Xerus2000/monsterutilities#68]
A lot of tracks will be wrongly chosed by it.
Example : Rootkit - Voyage (Kage Remix) redirects to a podcast.
Same for Julian Calor - Monster which redirects to Overcome (Epilogue)

**Comment by Xerus2000** [comment]
There is a test for it, we can fix this via TDD. I have previously wondered how accurate it is, thanks for the report!

**Comment by Xerus2000** [comment]
This is actually something caused by a recent API change, they are removing remixes from the title:
![image](https://user-images.githubusercontent.com/13354331/61994918-cbebaa80-b081-11e9-90df-13ca6d10df7b.png)
