### ISSUE TITLE
Rework Readme.md

### ISSUE THREAD

**Issue by defvs** [xerus2000/monsterutilities#72]
Some informations on it are old, deprecated. Most of the screenshots are not representative of the current program.

**Comment by Xerus2000** [comment]
Please add some more details about what you consider "deprecated" information. Is it just about the features?

**Comment by defvs** [comment]
I'll wait until my branches are merged and I'll do a readme overhaul, and a video tutorial.

**Comment by defvs** [comment]
Deprecated : 

- Connect.sid (now with the login dialog)

- Most of the screenshots have changed since (the downloader is very different)

- Some gradle tasks are missing

- gradle.properties should be explained

**Comment by Xerus2000** [comment]
What should be explained about gradle.properties? Which relevant gradle tasks are missing?
