### ISSUE TITLE
Add "streamer mode"

### ISSUE THREAD

**Issue by defvs** [Xerus2000/monsterutilities#74]
This would skip "Unlicensable tracks" (categorized by "CC" = N in the Catalog tab) and compilation albums (in Catalog tab, entries with "Various Artists")

**Comment by defvs** [comment]
I'll do this tommorow. Btw can you assign me to issues or do I need more permissions on the repo for this ?

**Comment by defvs** [comment]
defvs#4

**Comment by Xerus2000** [comment]
You can assign issues and labels yourself, I have given you the collaborator permission qutie some time ago.

**Comment by untuned** [comment]
Added suggestion, maybe add a toggle to not download non-licensable songs in the downloader?
