### ISSUE TITLE
Downloader should error out when downloaded file type is not music

### ISSUE THREAD

**Issue by defvs** [Xerus2000/monsterutilities#77]
Multiple ways to achieve this : Size check, if it's less than half a meg, highly probable that it's not music.

Better solution would be to check the "content-type" header of the server's response.

**Comment by Xerus2000** [comment]
Yes, implementing the latter would definitely be a good idea!

**Comment by defvs** [comment]
I'll do, assign me. I still cannot do it myself lol.

**Comment by Xerus2000** [comment]
here boi: https://github.com/Xerus2000/monsterutilities/invitations

**Comment by defvs** [comment]
Got it thanks, didn't receive it apparently.

**Comment by defvs** [comment]
So here are my findings : All tracks before Tails & Pauline Herr - Ghosted returns ``application/octet-stream`` and not the common MIME types (``audio/mpeg, audio/flac, audio/wav``). I haven't found a single one of thoses glitched flac yet so it's hard to tell if my fix is working or not. Check my PR for it.
