### ISSUE TITLE
Smart Select is broken

### ISSUE THREAD

**Issue by defvs** [Xerus2000/monsterutilities#81]
Latest ``master``, broken due to ad1808dd8df7f2dd03dc726ba043211038c369f8

The issue is that when calling the enum, ex. ``Release.Type.SINGLE`` and passing it in an argument in a function that requires a ``CharSequence``, the whole enum is passed and then by using it as a ``CharSequence``, we don't get its ``displayName`` but its "real name", example ``SINGLE`` instead of ``Single``

**Comment by Xerus2000** [comment]
Fixed by 7d774e26a23210bf5804b725132909e97e88ebe2
