### ISSUE TITLE
Can you make an installation guide?

### ISSUE THREAD

**Issue by yeh1234** [Xerus2000/monsterutilities#83]
I am not familiar with Java at all and this tool seems awesome. I would love to use it but it's hard to get started. Can you make a tutorial for complete newbies?

**Comment by Xerus2000** [comment]
Download & Install Oracle JRE: https://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html
Download jar from Releases & enjoy :)

**Comment by defvs** [comment]
Note that now with the installers, it is way more easier to install the software. You can find the installers in the release page. You still need to have a JRE installed but it'll error out if you don't. Closing this, it might be related to #72 with a better installation process
